name: cns
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12
  - babel=2.9.0
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - colorama=0.4.4
  - commonmark=0.9.1
  - cryptography=3.3.1
  - cudatoolkit=11.0.221
  - cycler=0.10.0
  - docutils=0.16
  - expat=2.2.10
  - freetype=2.10.4
  - future=0.18.2
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - intel-openmp
  - jinja2=2.11.3
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.11
  - libpng=1.6.37
  - libtiff
  - libuv=1.40.0
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - packaging=20.9
  - pcre=8.44
  - pillow=8.1.0
  - pip=21.0.1
  - pycparser=2.20
  - pygments=2.8.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - pytz=2021.1
  - qt=5.9.7
  - recommonmark=0.6.0
  - requests=2.25.1
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - snowballstemmer=2.1.0
  - sphinx=3.5.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - torchvision
  - torchaudio
  - pytorch
  - pip:
    - python-docs-theme-technopathy==0.7.10
    - sphinx-pdj-theme==0.2.1
    - sphinx-rtd-theme==0.5.1
